include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_NAME "solver")
set(CPACK_PACKAGE_VENDOR "werdfgy")
set(CPACK_PACKAGE_CONTACT "werdfgy@gmail.com")

set(CPACK_PACKAGE_VERSION "${PRINT_VERSION}")

if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION")
    set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION")
endif()
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Solver app for quadratic equations")

set(CPACK_PACKAGE_VERSION_MAJOR ${PRINT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PRINT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PRINT_VERSION_PATCH})

set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.31)")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "werdfgy")

include(CPack)
